name: CMake for Windows

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - uses: actions/checkout@v6
      with:
        repository: ci-cd-donizete/cmake-toolchain
        path: ${{github.workspace}}/cmake-toolchain

    - name: Install mingw-w64
      run: sudo apt update && sudo apt install -y mingw-w64 nasm

    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake-toolchain/toolchain-mingw64.cmake
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: translucent-sdl3.exe
        path: ${{github.workspace}}/build/translucent-sdl3.exe
        compression-level: 9

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: nightly
        make_latest: true
        token: ${{ secrets.GH_PAT }}
        files: ${{github.workspace}}/build/translucent-sdl3.exe
